version: '3'
services:
  #dungeon:
  #  build:
  #    context: .
  #  volumes:
  #    - ./dungeon_master:/app/
  #    - ./ladybug/data:/app/ladybug/data
  #  environment:
  #    - OPENAI_API_KEY=$OPENAI_API_KEY
  #    - DATABASE_PATH=/app/ladybug/data/dungeon-master.lbug
  #  ports:
  #    - "61799:61799"
  #  tty: true
  #  stdin_open: true
  #    command: "lein run"

  graphdb:
    image: ghcr.io/ladybugdb/explorer:latest
    volumes:
      - ./ladybug/data:/database
    environment:
      - LBUG_FILE=dungeon-master.lbug
    ports:
      - "8000:8000"
